name: zappy_meal
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  awesome_dialog: ^3.0.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.2
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.0.1
  flutter_screenutil: ^5.7.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.3
  flutter_zoom_drawer: ^3.0.4+1
  fluttertoast: ^8.2.1
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  go_router: ^6.5.7
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  image_picker: ^0.8.7+4
  intl: ^0.17.0
  logger: ^1.3.0
  lottie: ^2.3.2
  modal_bottom_sheet: ^3.0.0-pre
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  uuid: ^3.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  rename: ^2.1.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/icons/
    - assets/animations/
    - assets/images/
    - assets/translations/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
