name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  versioning:
    name: Install flutter and deps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "12.x"
          cache: gradle

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.1"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

  build:
    needs: versioning
    name: Build app bundle
    runs-on: ubuntu-latest

    steps:
      - name: Build app
        run: flutter build apk

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: App Bundle
          path: build/app/outputs/bundle/release/app.aab
