name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  version:
    name: Build app bundle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"

      - name: Install dependencies
        run: flutter pub get

  build:
    name: Build app bundle
    runs-on: ubuntu-latest

    steps:
      - name: Build app
        run: flutter build appbundle

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: App Bundle
          path: build/app/outputs/bundle/release/app.aab
